team-dopamine/husk-web

.husky/commit-msg, .husky/pre-commit, commitlint.config.ts, package-lock.json, package.json
커밋 메시지 일원화를 위한 Conventional Commit 설정 필요성 대두
- commitlint 관련 패키지 설치
- husky 설치
- `./commitlint.config.js` 작성
- husky hook 에 commit-msg 추가하기
- `./husky/pre-commit` 파일 수정
- 페어 프로그래밍
=> Convetional Commit 설정

README.md
프로젝트 진행 시 용이한 패키지 구조 파악을 위함
프로젝트 패키지 구조 `README.md`에 작성
페어 프로그래밍
=> 프로젝트 구조 작성

.eslintrc, .prettierrc, commitlint.config.ts, package-lock.json, package.json, public/index.html, src/App.tsx, src/index.css, src/index.tsx, tsconfig.json
프로젝트 진행 시 코드의 가독성 및 일관성을 높이기 위함
- `ESLint` 설정
- `Prettier` 설정
페어 프로그래밍
=> chore/HK-50: Prettier & ESLint 설정

tsconfig.json
상대경로로 인해 프로젝트 디렉토리 구조 파악이 어려워서 간결하게 경로를 설정하고자 함
- `tsconfig.ts` 에 절대경로 설정
페어 프로그래밍
=> chore/HK-51: 절대경로 설정

.github/workflows/cd.yml, .github/workflows/ci.yml, tsconfig.json
코드 구현 시 어떤 이벤트가 발생했을 때 자동으로 특정 작업을 진행하도록 하기 위함
- `workflows` 폴더 내부에 `ci.yml`와 `cd.yml` 설정
없습니다~
=> chore/HK-59: CI/CD 파이프라인 구축

src/pages/main/content/index.style.tsx, src/pages/main/content/index.tsx
- [Jira's HK-68 참고](https://team-dopamine.atlassian.net/browse/HK-68?atlOrigin=eyJpIjoiMjA4YTNhMjdlZmFjNGViOTk0MjlmM2JkZGFkMjNjODAiLCJwIjoiaiJ9)
- 기존 메인 페이지의 'Lorem Ipsum' 같은 문자열에서 서비스에 맞는 문자열로 페이지를 수정하기 위함
- Img -> ContentImage 네이밍 변경
- TextContainer 별도 구현
- 4개의 기능 소개 추가
- X
=> Fix(HK-68): 메인 페이지 수정

.github/workflows/cd.yml, Dockerfile
- [HK-78](https://team-dopamine.atlassian.net/browse/HK-78?atlOrigin=eyJpIjoiODc2ZTkxNmNmNTY1NGZjZGE5NmZmY2I3YjBlMmMwYTkiLCJwIjoiaiJ9) 참고
- 서버 다이어트([HK-77](https://team-dopamine.atlassian.net/browse/HK-79?atlOrigin=eyJpIjoiNjg0YTQxZjhhZGU2NDI5Mzg2OTcxMWQ3YmQyNjY0NWUiLCJwIjoiaiJ9) 참고) 차 EC2 인스턴스 삭제 필요성 대두
- Dockerfile 작성
- GitHub Actions Secrets 수정
- SERVER_HOST 수정
- DOCKER_USERNAME 추가
- DOCKER_PASSWORD 추가
- Dockerfile에 각 라인의 역할을 작성해놨으니 참고하시면 좋을 것 같습니다.
- 기존 인스턴스 삭제를 통한 AWS 비용 절감 기대
[HK-78]: https://team-dopamine.atlassian.net/browse/HK-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HK-77]: https://team-dopamine.atlassian.net/browse/HK-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature (HK-78): Deploy 파이프라인 수정

src/App.tsx, src/pages/sign-up/read-terms/index.style.tsx, src/pages/sign-up/read-terms/index.tsx, src/pages/sign-up/read-terms/read-terms-content/index.style.tsx, src/pages/sign-up/read-terms/read-terms-content/index.tsx
- [HK-82](https://team-dopamine.atlassian.net/jira/software/projects/HK/boards/2/backlog?selectedIssue=HK-82&atlOrigin=eyJpIjoiMmNjZGE3M2Q5MDc1NGI0Y2JjYzc4Mjc2YTVlYjJhMTYiLCJwIjoiaiJ9) 참고
- 사용자가 회원가입 시 약관동의를 할 수 있는 페이지 구현
- 약관동의 페이지 router 연결(26b8143cf6f3f357627ac9dae0e3f2ad580a3ca7)
- 사용자로부터 약관동의 받는 페이지 구현(f8cad8cd9922bc6fdcd225bf2f18ea261c35eab3)
[HK-82]: https://team-dopamine.atlassian.net/browse/HK-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-82): 약관동의 페이지 구현

.gitignore, package-lock.json, package.json, src/api/axios.tsx
- [HK-71](https://team-dopamine.atlassian.net/browse/HK-71?atlOrigin=eyJpIjoiNDdlZTU5NDA4MjZlNDk2MTliZmI1MzQwYmNhOTIzMDAiLCJwIjoiaiJ9) 참고
-  API 연동 시 초기 세팅값 설정 필요성 대두
- `axios` 라이브러리 설치 (aa082e33456c5a0081ac8841e22ea074869b8a48)
- `baseUrl` 지정 (9cc4aad8ad7d0903983d237865ced12a734b372d)
- X
[HK-71]: https://team-dopamine.atlassian.net/browse/HK-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-71): API 초기 설정

src/api/verify-code/index.tsx, src/components/sign-up/email-verify/index.tsx, src/pages/sign-up/content/index.tsx
- [HK-88](https://team-dopamine.atlassian.net/browse/HK-88?atlOrigin=eyJpIjoiZmQxYjQ4MmYwNTM4NGI5YjhkYWNiNDE2NzRlZTA4NjAiLCJwIjoiaiJ9) 참고
- 이메일로 받은 인증코드 입력받아 검증하기 위한 API 연결
- 인증코드 검증 api 호출 로직 구현(b03e18ef8f66e40a9622907fb78902c44f5e0a8c)
- 인증코드 입력 후 **Verify** 버튼 클릭 시 인증코드 검증(fdd6ff033daa8162e7f1fa2da14270712a687dd1)
- 인증코드 유효성 검증 후 next 버튼 활성화(07485a4c6c9c51ade542775285d155e9bcc7523a)
X
[HK-88]: https://team-dopamine.atlassian.net/browse/HK-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-88): 인증코드 검증 API 연결

src/App.tsx, src/api/axios.tsx, src/api/context/auth-context/index.tsx, src/api/context/auth-provider/index.tsx, src/api/context/auth-util/index.tsx, src/api/context/use-auth/index.tsx, src/api/sign-in/index.tsx, src/pages/sign-in/sign-in-email/content/index.tsx, src/pages/sign-up/content/password/index.tsx
- [HK-102](https://team-dopamine.atlassian.net/browse/HK-102?atlOrigin=eyJpIjoiY2U3ZTMxMDkwOGRjNGFmMjkzZGZiYWRlOTAxYmY4NjEiLCJwIjoiaiJ9) 참고
- 로그인 API 호출 로직 구현(058afe82c0a4ca01a948609c6c1298f5f1404c09)
- 로그인 API 연동(0039eb4775de2993e0a1ce26167ab2c7fa13be6b)
- `Context API` 활용하여 accessToken을 **localStorage**에 저장(edd99981489bab66cbb734dd15264423508950c5)
- Login -> Logout  버튼UI는 추후 로그아웃 API 연결 후 구현 예정
- Merge 충돌 이 브랜치에서 같이 해결(63c21ff597c62fe4b4682b21d476267f444848dc)
[HK-102]: https://team-dopamine.atlassian.net/browse/HK-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-102): 일반 로그인 API 연결

src/App.tsx, src/pages/reset-password/content/index.style.tsx, src/pages/reset-password/content/index.tsx, src/pages/reset-password/index.tsx
- [HK-105](https://team-dopamine.atlassian.net/browse/HK-105) 참고
- 비밀번호 재발급 페이지 구현(9766945e70c7cde0e1db6742e46035fc7a4d0483)
- 아직 UI만 만들어서 로직 처리하는 부분은 미흡합니다!
[HK-105]: https://team-dopamine.atlassian.net/browse/HK-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-105): 비밀번호 재발급 페이지

src/api/reset-password/index.tsx, src/components/sign-up/email-verify/index.tsx, src/pages/reset-password/content/index.tsx
- HK-99([https://team-dopamine.atlassian.net/browse/HK-99]) 참고
- 사용자가 비밀번호를 잊었을 경우, 재발급 하기 위함
- 비밀번호 재발급 API 호출 로직 구현(4304c3ad77e56bdc6f7659f7331174f5c6e87154)
- 자세한 설명은 코드에 댓글로 달게요!
=> Feature(HK-99): 비밀번호 재발급 API 연동 구현

src/pages/temp-update-password/verify/index.tsx
- [이전 PR 참고](https://github.com/team-dopamine/husk-web/pull/36#issue-2884190738)
- `setLoading(true);` 상태 추가
=> Feature(HK-116): loading 상태 추가

src/App.tsx, src/components/dashboard-frame/index.style.tsx, src/components/dashboard-frame/index.tsx, src/components/dashboard-header/index.style.tsx, src/components/dashboard-header/index.tsx, src/components/sidebar/index.style.tsx, src/components/sidebar/index.tsx, src/pages/dashboard/content/index.tsx, src/pages/dashboard/index.style.tsx, src/pages/dashboard/index.tsx
- [HK-117](https://team-dopamine.atlassian.net/browse/HK-117)참고
- 사용자가 dashboard 페이지를 사용하기 위함
-  DashboardHeader, DashboardFrame, Sidebar 등 구현(d4571d14aa8f060175b09f9d835bdd484eedb60d)
- 정보수정, 로그아웃 버튼 UI 수정(1aa1b3c654f6400649442c60b7295d38194c04de)
-  amplify에 배포된 대시보드 페이지 확인 후 피드백 부탁드려요!  
[HK-117]: https://team-dopamine.atlassian.net/browse/HK-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-117): dashboard 페이지 구현

src/components/dashboard/modal/index.tsx
- [HK-120](https://team-dopamine.atlassian.net/browse/HK-21?atlOrigin=eyJpIjoiNWYzMjNkOWMwMzVhNGVhNmJjZDZiNWJmODQ4YjFiNmMiLCJwIjoiaiJ9) 참고
- `useModal`훅을 사용하여 Modal 상태 관리 개선
[HK-120]: https://team-dopamine.atlassian.net/browse/HK-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor(HK-120): useModal Hook 적용하여 Modal 상태 관리 개선

src/api/keychains/register-keychain/index.tsx, src/components/dashboard/button/index.tsx, src/components/dashboard/modal/index.tsx, src/pages/test/index.tsx
- [HK-121](https://team-dopamine.atlassian.net/browse/HK-121)참고
- 모달창에서 얻은 키체인 값을 등록하고자 함
- 키체인 등록 API 요청 함수 추가(47a509b1dfd0abdeeffc6d8f33e54806418f0fb4)
- 키체인 등록 API 연동(4913d68af4e847ac2e691c52ff9356aa15e74e7a)
-  모달 입력 상태 관리 로직 추가(b59b0eaced953a9d3aa57a630ccccb8db86776cf)
- ButtonGroup 컴포넌트 호출 제거(d5ef9e4eccfa23fcb72a2ef9226f77bd7b78e5fc)
test 페이지에서 ButtonGroup 컴포넌트 호출하는 부분 삭제했습니다,,!
[HK-121]: https://team-dopamine.atlassian.net/browse/HK-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-121): 키체인 등록 API 구현 및 연동

.github/workflows/cd.yml, Dockerfile
- `퍼블릭ip → 도메인` 연결 필요성 대두.
- `aws amplify` 사용을 위한 https 프록시 설정.
- 사용자들이 이용할 수 있는 서비스 도메인 제공 필요.
- Route 53을 활용한 도메인 연결
- Nginx 설정을 통한 리버스 프록시 설정
- Dockerfile 및 cd 파일 일부 수정
- 해당 PR merge 후 api 연동 및 오류 사항이 없는지 확인해보아야 할 것 같아서 수시간내로 PR이 여러번 올라올 수 있을 것 같습니다.
=> Chore(HK-135): Nginx 설정에 따른 Dockerfile 및 CD 명령어 수정

src/api/keychains/keychain-delete/index.tsx, src/components/dashboard/button/index.tsx, src/components/dashboard/keychain-read-modal/index.tsx, src/pages/test/index.tsx
- [HK-128](https://team-dopamine.atlassian.net/browse/HK-128?atlOrigin=eyJpIjoiYzM4NjNhMWQzNmFhNGI1MmEzNzkyYjliNzNhNzhiY2UiLCJwIjoiaiJ9) 참고
- 사용자가 키체인 삭제를 하기 위함
- 키체인 삭제 API 호출 로직 구현(385dfd8feaf75661e57a14b8cc511e4d3e4bc304) ,(2c2ee6e2d662a9c0984f5b1c862adf24e50c5eca)
- 우선 ButtonGroup은 그대로 뒀습니다!
[HK-128]: https://team-dopamine.atlassian.net/browse/HK-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-128): 키체인 삭제 API 호출 구현

package-lock.json, package.json, src/App.tsx, src/api/socket/index.tsx, src/components/terminal/index.tsx, src/pages/ssh-connection/index.tsx, src/pages/terminal/index.style.tsx, src/pages/terminal/index.tsx
- [HK-145](https://team-dopamine.atlassian.net/browse/HK-145?atlOrigin=eyJpIjoiMjg0MzE5YTVlNDU5NDYyZWJjMDJlM2RjY2Y1MDg2YzgiLCJwIjoiaiJ9) 참고
- 서비스 핵심 기능 이용을 위해 웹터미널 기능 필요성 대두
- `xTerms` 패키지를 활용한 웹터미널 구현(aecd6a350183ccdfe1be4286ff0a00b0116c2fc6), (24158241ae7a7a986747a862344796cade19a8f1)
- 웹소켓 통신을 통한 대화형 웹터미널 연결(f2df4e91bd01bf46f157b2ef964bf40dd9c369a2)
- 웹소켓 클라이언트 구현(bd70e01f1a164a5e002e3809e8c1d6329cdcae6b)
<details><summary>웹터미널 연결 테스트</summary>
</details> 
- 커넥션 접속 요청 시 사용하는 커넥션 `id` 값을 `useParams()`를 통해 전달(f67f32b4687c1a6a7d2297a084d872c768958037) 
[HK-145]: https://team-dopamine.atlassian.net/browse/HK-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature(HK-145): 웹터미널 구현

.github/workflows/cd.yml
- [pr-145](https://github.com/team-dopamine/husk-web/pull/56) cd 오류 발생
- `cd.yml`의 ubuntu 버전 수정
=> Fix(HK-149): cd.yml ubuntu 버전 업데이트

src/api/ssh-connections/ssh-register/ssh-connection-register/index.tsx, src/components/dashboard/button/saveButton/index.tsx, src/components/dashboard/modals/register-modal/index.tsx, src/components/dashboard/modals/register-modal/types/index.tsx, src/pages/keychain/index.tsx, src/pages/ssh-connection/index.tsx
- [HK-129 참고](https://team-dopamine.atlassian.net/browse/HK-129)
- SSH 커넥션 정보를 저장하고자 함
- SSH 커넥션 저장 api 연동(24da1d752061544be4048047fe276dbde4163a93)
- SSH 커넥션 api 호출(fe2050962cae91f8dee71c657a67ecb5f76f9a3f)
- 페이지 값에 따른 api 호출 기능 추가(412a860abefa55d0dda15c17bbe6b20a1841531b)
- SSH 커넥션 등록 모달 구현(052e561535a0cdff044194f0ecb17b9dd8d8c7af)
- 깃허브 이슈로 커밋이 2번 돼서 Problem Solving에 있는 커밋 4개만 보셔도 됩니당
=> Feature(HK-129): SSH 커넥션 저장 API 연동

src/components/dashboard/cards/keychain-card/index.tsx, src/pages/keychain/index.tsx
- [HK-140](https://team-dopamine.atlassian.net/browse/HK-140) 참고
- 불필요한 기능 제거 및 카드 값 수정
- 불필요한 기능 제거 및 카드 값 수정(458fc16ae9e21fc28662a025506ef6ccfb96c6e9)
- 아래와 같은 읽기 모달에 접근할 수 있는 두 가지 기능을 제공했으나, 아이콘의 기능이 직관적으로 드러나지 않는 문제 발생 → 카드 전체 클릭 기능 제거
[HK-140]: https://team-dopamine.atlassian.net/browse/HK-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor(HK-140): Keychain 페이지 리팩토링

src/api/ssh-connections/ssh-read/index.tsx, src/api/ssh-connections/ssh-update/index.tsx, src/components/dashboard/cards/sshConnection-card/index.tsx, src/components/dashboard/modals/sshConnection/handlers/index.tsx, src/components/dashboard/modals/sshConnection/index.tsx, src/components/dashboard/modals/types/index.tsx
- [HK-143 참고](https://team-dopamine.atlassian.net/browse/HK-143)
- 사용자가 저장한 SSH 커넥션을 수정하기 위함
- 불필요한 type 제거와 코드 정리(5edff9f428e3be3c37ccee6fce0b18713d0028d6)
- SSH 커넥션 수정 API 연동(09a24df4f934cb7b71e0400393e9fb9ec5cce147)
- SSH 커넥션 수정 API 요청 및 관련 함수 구현(a68315cdffa685814bdb3f24b9fb39cee0124c5e)
문제 있으면 말해주세요 ᓚᘏᗢ
=> Feature(HK-143): SSH 커넥션 수정 API

src/App.tsx, src/api/axios.tsx, src/components/header/index.tsx, src/pages/main/content/index.tsx, src/pages/reset-password/content/index.tsx, src/pages/sign-in/content/index.tsx, src/pages/sign-in/sign-in-github/index.tsx, src/pages/sign-in/sign-in-google/index.tsx, src/pages/sign-up/content/terms/content/index.tsx
- 지난 리팩토링 후 github, google 로그인 오류
- 기존의 redirect uri와 관련된 경로 수정
=> Refactor(HK-161): 경로 수정

src/components/terminal/index.tsx, src/pages/terminal/index.tsx
- [HK-159](https://team-dopamine.atlassian.net/browse/HK-159) 참고
- 입력창에서 방향키 입력 시 커서가 의도치 않게 움직이는 문제, 연속 백스페이스 시 문자열이 지워지지 않는 오류를 해결하고자 함
- 키보드 입력을 받기 위한 메서드 구현(420f950)
- 방향키를 서버로만 전달하기 위한 조건문 구현(bc9a08a)
- 연속 백스페이스 입력 시 작동되지 않는 오류 해결
[HK-159]: https://team-dopamine.atlassian.net/browse/HK-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(HK-159): 웹터미널 버그 수정
