team-dopamine/husk-web

- src/App.tsx
- src/components/footer/index.style.tsx
- src/components/footer/index.tsx
- src/pages/main/index.style.tsx
- src/pages/main/index.tsx
- [HK-63](https://team-dopamine.atlassian.net/browse/HK-63?atlOrigin=eyJpIjoiZDVlMDZiNzNjMDQ3NGE1N2E1MDhlMjFmZTA5MzE3NWYiLCJwIjoiaiJ9)
- 서비스 약관, 사용자 지원, 보조 네비게이션을 포함하는 컴포넌트 필요성 대두
- Footer 컴포넌트 구현
- Main 페이지 레이아웃 구현
1. AWS Amplify에서 Header와 Footer를 포함하는 UI를 확인하기 위해 MainPage 레이아웃을 가볍게 구현해 보았습니다.
- 추후 MainPage 상세 구현 시에는 수정하셔도 무방합니다.
2. 현재 `@Components`, `@Page`와 같은 절대 경로가 동작하지 않고 있습니다. 
```
ERROR in ./src/pages/main/index.tsx 5:0-40
Module not found: Error: Can't resolve '@components/footer' in '/Users/jinu/Desktop/workspace/dopamine/husk-web/src/pages/main'
```
- 따라서 우선적으로는 상대 경로로 구현(`'../../components/footer';`)하였으나 별도 PR을 통해 버그 픽스을 위한 작업을 해야할 것 같습니다.
[HK-63]: https://team-dopamine.atlassian.net/browse/HK-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> Feature(HK-63): Footer 컴포넌트 구현

- package-lock.json
- package.json
- src/App.tsx
- src/components/header/index.style.tsx
- src/components/header/index.tsx
- src/pages/sign-in/content/index.style.tsx
- src/pages/sign-in/content/index.tsx
- src/pages/sign-in/index.style.tsx
- src/pages/sign-in/index.tsx
- [Jira's HK-69 참고](https://team-dopamine.atlassian.net/browse/HK-69?atlOrigin=eyJpIjoiOTdmMWNlYTQ1OTc5NGZjZTljYjc0ZTMxNzY0NTdlMGUiLCJwIjoiaiJ9)
- 사용자가 로그인 계정 유형을 선택하거나 회원가입을 진행하기 위한 사전 페이지 구현
- `react-router-dom` 패키지 설치 및 적용을 통한 Router 설정
- 로그인 페이지 구현
- Third-Party 로그인 버튼은 각 플랫폼별 가이드 라인을 참고하여 수정이 필요할 것 같아 추후에 이야기 나눠보면 좋을 것 같습니다.
- [참고](https://brunch.co.kr/@bf6b5403fa344c4/43)
> Feature(HK-69): 로그인 페이지 구현

- craco.config.js
- package-lock.json
- package.json
- src/pages/main/index.tsx
- src/pages/sign-in/index.tsx
- tsconfig.json
- [HK-65](https://team-dopamine.atlassian.net/browse/HK-65?atlOrigin=eyJpIjoiZWQ4ZjkzN2Q1N2Y0NDA4ZmJhNzAzN2UwN2FjMGY2MjAiLCJwIjoiaiJ9)
- [HK-51](https://team-dopamine.atlassian.net/browse/HK-51?atlOrigin=eyJpIjoiMjhmMDY0ZThiNTI1NGZlNWEyNzhlYTE0ODA5NmQ1NGIiLCJwIjoiaiJ9) 에 설정한 절대경로 적용 안됨 이슈 해결
- `craco` 라이브러리 설치 (ca42cf25d726c5cd7720a57a26500053e149f95a)
- `tsconfig.json`의 `baseUrl` 및 `path` 수정 (9eaf072ae6b06216ddc20133aae90f038a79cdf7)
- 기존의 상대경로로 설정되어 있던 파일들 절대경로로 수정완료(4917e9077547b36ff7cf6f79ef01caa336cccf6e)
[HK-65]: https://team-dopamine.atlassian.net/browse/HK-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HK-51]: https://team-dopamine.atlassian.net/browse/HK-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
> Fix(HK-65): 절대경로 오류 수정

- src/App.tsx
- src/components/sign-up/email-verify/index.style.tsx
- src/components/sign-up/email-verify/index.tsx
- src/components/sign-up/index.style.tsx
- src/components/sign-up/index.tsx
- src/pages/sign-up/content/index.style.tsx
- src/pages/sign-up/content/index.tsx
- src/pages/sign-up/index.style.tsx
- src/pages/sign-up/index.tsx
- [Jira's HK-70 참고](https://team-dopamine.atlassian.net/browse/HK-70?atlOrigin=eyJpIjoiMjE2MjBkMDE0ZmRlNDlhMWI5MzcyMmQxY2RiMjg1YzYiLCJwIjoiaiJ9)
- 사용자가 이메일 인증 코드를 통해 유효성을 검증하여 회원가입을 진행하기 위한 페이지 구현
- 회원가입 페이지 router 설정(cb292c486612383924b6801c0270481837afcd92)
- 사용자로부터 이메일을 입력 받아 해당 이메일로 인증코드를 보낼 수 있는 페이지 구현(aa206a6)
- `previous`, `Next`버튼을 통해 페이지 이동(aa206a6)
-  Api 연결 후 따로 수정해야 할 부분은 `TODO:` 를 통해 기록해두었음. 추후 api 연결 시 수정 예정.
- 이메일 인증 페이지만 우선 구현해뒀는데 다음 단계 페이지(`Ex.비밀번호 설정, 약관 동의, 아이디/비번 찾기`) 는 따로 브랜치를 파서 진행하는 건 어떨 지 의견 부탁드립니다!
> Feature(HK-70): 일반 회원가입 이메일 인증 페이지 구현

- src/App.tsx
- src/components/sign-up/password-setting/index.style.tsx
- src/components/sign-up/password-setting/index.tsx
- src/pages/sign-up/password/index.style.tsx
- src/pages/sign-up/password/index.tsx
- src/pages/sign-up/password/password-content/index.style.tsx
- src/pages/sign-up/password/password-content/index.tsx
- [Jira's HK-81 참고](https://team-dopamine.atlassian.net/jira/software/projects/HK/boards/2/backlog?selectedIssue=HK-81&atlOrigin=eyJpIjoiNDIwZDQ5ZWJjYzQ4NDRmYTgyNWNlNjk3YzRiMWVhNGIiLCJwIjoiaiJ9)
- 사용자가 회원가입 시 비밀번호를 설정하기 위한 페이지 구현
- 비밀번호 설정 페이지 router 연결(ef107a890fcac7c17c045bc859031c8762edd051)
- 사용자로부터 사용할 비밀번호를 입력 받아 비밀번호 유효성 검사(274495bab6bb45146221511ba9c475fc6208334d)
- `previous`, `Next` 버튼을 통해 페이지 이동(76fd95bbc0452a7bf462e42eb681c84f12b76a67)
- 비밀번호 생성 조건은 **8~16자 영문 대 소문자, 숫자, 특수문자를 포함**으로 설정
:speech_balloon:
--
- 추후 리팩토링 작업 필요
- 라우터 설정
- 디렉토리 구조
- 메인페이지, 로그인페이지, 회원가입 페이지에서 공통적으로 사용되는 요소(Header, Footer) 혹은 `ButtonGroup` 등은 공통 컴포넌트로 설정하면 구현할 때 더 편리해 질 것 같습니다!
> Feature(HK-81): 일반 회원가입 비밀번호 설정 페이지 구현

- .github/workflows/cd.yml
- [이전 PR](https://github.com/team-dopamine/husk-web/pull/15) 중 버그 발견으로 인한 수정
- 대상 브랜치 수정 (develop -> main)
- ssh 접속 방식 수정 (password 사용 -> key 사용)
미처 확인하지 못해서 workflow fail이 발생했네요...ㅎㅎ 죄송합니다.
> Fix(HK-78): deploy workflow의 trigger 브랜치와 ssh 접속 방식 수정

- .github/workflows/cd.yml
- Dockerfile
- package-lock.json
- package.json
- [이전 PR](https://github.com/team-dopamine/husk-web/pull/16) 참고
- 이전 PR의 Dockerfile을 통한 `docker run` 명령어 시 EC2 인스턴스(t2.micro)가 다운되는 현상이 발생하였음
- 임의의 인스턴스(t2.medium)에서 실행할 경우 정상적으로 실행되는 것을 확인
- 이를 통해 보다 경량의 도커 컨테이너가 필요하다고 판단하였음
- 멀티 스테이지 빌드 적용 (약 87% 절감)
| 적용 전 | 적용 후 |
| ------ | ------ |
| ![image](https://github.com/user-attachments/assets/b58e436a-66b7-4526-ba15-ac37d21eb7ba) | ![image](https://github.com/user-attachments/assets/1d81d6ff-9722-44f1-9793-8eaa13c92b1a) |
- node 이미지 수정 (경량의 slim 이미지 사용)
- 기존의 더 많은 레이어들과 불필요한 빌드 도구들 포함하는 빌드 방식에서 필수적인 런타임 환경만 포함하도록 수정하였음 (빌드 도구와 소스 코드가 최종 이미지에서 제외)
- X
> Fix(HK-78): Docker 멀티 스테이지 빌드 적용

- .github/workflows/cd.yml
- [이전 PR 참고](https://github.com/team-dopamine/husk-web/pull/18)
- 기존 deploy workflow에서 컨테이너명을 명시하지 않았음
- 이로 인해 기존 웹 서비스가 종료되지 않아 포트 충돌로 인해 새로운 버전의 서비스가 배포되지 않는 상황 발생
- deploy workflow의 `docker run` 구문에서 컨테이너 실행 시 컨테이너명 명시
- X
> Fix(HK-78): docker 컨테이너 실행 시 컨테이너명 명시

- src/api/read-terms/index.tsx
- src/pages/sign-in/content/index.tsx
- src/pages/sign-up/read-terms/read-terms-content/index.style.tsx
- src/pages/sign-up/read-terms/read-terms-content/index.tsx
- [HK-94](https://team-dopamine.atlassian.net/browse/HK-94?atlOrigin=eyJpIjoiZTMwYzcxYTBjNGU5NDA3N2I5OWIxYWU1MWZkYmMzNGEiLCJwIjoiaiJ9) 참고
- 회원가입 전 사용자에게 서비스 이용 약관을 공지하고 동의를 받기 위함
- 서비스 이용 약관 api 호출 로직 구현(3ed124c3f43c8df75e1143e8f4a01e63ccedb7e7)
- 서비스 이용 약관 api 연동(9198902d5dcab362488eaf7b284c731f8f34e193)
- 약관 동의를 반드시 해야 `Next` 버튼을 활성화, 이메일 유효성 검사 페이지로 넘어가도록 구현
- `이메일 검증` -> `비밀번호 설정` -> `약관동의` 순서에서 `약관동의` -> `이메일 검증` -> `비밀번호 설정` 로 변경
[HK-94]: https://team-dopamine.atlassian.net/browse/HK-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-94): 서비스 사용자 이용 약관 조회 API 연동

- src/api/sign-up/index.tsx
- src/components/sign-up/email-verify/index.tsx
- src/components/sign-up/password-setting/index.tsx
- src/pages/sign-up/content/index.tsx
- src/pages/sign-up/password/password-content/index.tsx
- [HK-91](https://team-dopamine.atlassian.net/browse/HK-91?atlOrigin=eyJpIjoiMzQ4MzAyY2JkMmZjNDZiM2IzYTU2OGUwNmQyNTg0N2UiLCJwIjoiaiJ9) 참고
- 사용자로부터 입력받은 `email` 및 `password`를 통해 회원가입 하기 위한 API 연결
- 회원가입 api 호출 로직 구현(95eaed29ba3e689563f2480b0e28460f78e961d3)
- `/sign-up` 페이지에서 사용자로부터 입력 받은 `email`을 **navigate**를 통해 `/password` 페이지로 이동 시 함께 전달(9376b53dadeb7f49ba8dad0c18cefc88795211eb)
- `/password` 페이지에서 사용자로부터 입력 받은 `password`는 `email`과 함께 서버로 바로 POST
- email과 password를 `sessionStorage`로 저장하였으나, 보안 이슈를 비롯한 문제로 수정함
[HK-91]: https://team-dopamine.atlassian.net/browse/HK-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-91): 회원가입 API 연결

- src/App.tsx
- src/pages/sign-in/content/index.tsx
- src/pages/sign-in/sign-in-email/content/index.style.tsx
- src/pages/sign-in/sign-in-email/content/index.tsx
- src/pages/sign-in/sign-in-email/index.tsx
- [HK-103](https://team-dopamine.atlassian.net/browse/HK-103?atlOrigin=eyJpIjoiMTk1NjE0NDI0MzkzNGRhNmE4ZGE0N2U2MTQxNjA5MGEiLCJwIjoiaiJ9) 참고
- 사용자가 일반 회원가입을 통해 생성한 계정으로 로그인 할 수 있는 페이지
- `email`, `password` 입력필드 구현 (771bcd234b5bd96bc8d24414babf287db4775d25)
- `/sign-in` 의 `Continue with Email` 클릭 시 해당 페이지로 이동 (974515cd74411e1cf1bfbcea71eceb918084c5d9)
- `/auth-sign-in` 으로 일반 로그인 경로 추가(497489c464a1644d2df72f0f1853ccaf96788645)
- Amplify 통해 확인 가능합니다!
[HK-103]: https://team-dopamine.atlassian.net/browse/HK-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-103): 일반 로그인 페이지 구현

- src/api/sign-in/github/index.tsx
- src/index.tsx
- src/pages/sign-in/content/index.tsx
- src/pages/sign-in/index.tsx
- src/pages/sign-in/sign-in-github/index.tsx
- [HK-93](https://team-dopamine.atlassian.net/browse/HK-93?atlOrigin=eyJpIjoiOWExM2E3NGY3N2RlNGU1Mzk0N2UzMWE1ZjU1ZDNkNzkiLCJwIjoiaiJ9) 참고
- 깃허브 계정을 통해 HUSK 서비스에 로그인하고자 함
- 깃허브 로그인 API 호출 로직 구현 (21adf9d8690f474de67f4d93a45923e7c1e7c059)
- 깃허브 로그인 API 호출 (b60fe762bb82d69c41217af0942a32c431e8d0dd)
- API가 두번씩 호출되는 오류가 발생하여 index.tsx의 `<React.StrictMode>` 삭제하였습니다
[HK-93]: https://team-dopamine.atlassian.net/browse/HK-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-93): GitHub 로그인 API 구현

- src/api/sign-in/github/index.tsx
- src/api/sign-in/google/index.tsx
- src/pages/sign-in/index.tsx
- src/pages/sign-in/sign-in-google/index.tsx
- [HK-92](https://team-dopamine.atlassian.net/browse/HK-92) 참고
- 구글 로그인 API 응답 부분 수정 (cf0fb98142faae0a2bf192407fbcb9a04b1d0874)
- 기존에는 응답 값 자체를 받아와서 오류가 생긴 거 같습니다. 따라서 response.statusCodeValue로 접근하여 status값을 받아오도록 수정했습니다.
[HK-92]: https://team-dopamine.atlassian.net/browse/HK-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix(HK-92): 구글 OAuth status값 받아오기 수정

- src/api/axios.tsx
- src/api/context/auth-context/index.tsx
- src/api/context/auth-provider/index.tsx
- src/api/context/auth-util/index.tsx
- src/api/sign-out/index.tsx
- src/components/frame/index.tsx
- src/components/header/index.tsx
- src/pages/sign-in/sign-in-email/content/index.tsx
- src/pages/sign-in/sign-in-github/index.tsx
- src/pages/sign-in/sign-in-google/index.tsx
- [HK-98](https://team-dopamine.atlassian.net/browse/HK-98?atlOrigin=eyJpIjoiNzg0Njg5OTZmODRkNDczNWExYzZkODExZDdkYTA3NTkiLCJwIjoiaiJ9) 참고
- 사용자가 로그아웃을 할 수 있도록 API 구현
- refreshToken을 저장하도록 context api에 구현(54728da6d0845f942b1fb50c3ccb2351b41c8cdd)
- accessToken을 헤더에, refreshToken을 바디에 담아서 서버로 POST (15793a9e1214d5c166bf8e321b07d10654f2a680)
- 로그아웃 api 연동 구현(9d097dbd2aaee5e4bdf820f6f1ff5cad101d78cc)
- 로그인 상태 시 LoginButton의 Text -> Logout,  Logout 호출 시 -> Login으로 변경하도록 구현
- 그 외 불필요 로직 및 코드 삭제(278f14b138a29fa1b15e63745718ce66340f1a88), (14effd231fd362bb0883dfd469cf959febfef919)
[HK-98]: https://team-dopamine.atlassian.net/browse/HK-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-98): 로그아웃 API 연결

- src/api/context/auth-context/index.tsx
- src/api/context/auth-provider/index.tsx
- src/api/withdraw/index.tsx
- src/components/header/index.style.tsx
- src/components/header/index.tsx
- [HK-100](https://team-dopamine.atlassian.net/jira/software/projects/HK/boards/2/backlog?selectedIssue=HK-14&atlOrigin=eyJpIjoiYmUzMDU4N2E4ZWIwNDZiZGFiYmIwYWM2ZWIzODM3MDMiLCJwIjoiaiJ9) 참고
- 사용자가 서비스를 탈퇴할 수 있도록 하기 위함
- 서비스 계정 탈퇴 api 호출 로직 구현(21b142b89bb39aa36b0569d5c6b3ba86ab64468c)
- 탈퇴하기 버튼 클릭 시 서비스 계정 탈퇴 api 호출 (206cb0f139a9c8c904be4689ff3030cf20880afd)
- 우선 임의로 로그인 옆에 탈퇴하기 버튼 만들어두었음(9bac2034a18fc2bbd62b8c1661c26b0f1f02dc55)
- 추후 위치 수정 예정 및 탈퇴 확인 알림 (`ex`회원탈퇴 하시겠습니까?) 메시지 추가 예정이라 **TODO:** 로 표시
[HK-100]: https://team-dopamine.atlassian.net/browse/HK-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-100): 서비스 계정 탈퇴 API 연동 구현

- .github/workflows/cd.yml
- 이전 PR 참고(https://github.com/team-dopamine/husk-web/pull/45)
- PR merge 후 CD 실패. 
- `docker run` 명령어 실행 시 포트 수정 필요
- `8080:80` 에서 `3000:80`으로 수정
- 죄송합니다..😢
> Fix(HK-135): 도커 실행 시 포트 매핑 수정

- src/pages/main/content/index.tsx
- [(HK-138)](https://team-dopamine.atlassian.net/browse/HK-138) 참고
- 로그인 상태에 따른 홈 화면 '시작하기' 버튼 라우팅
- 로그인 상태: /dashboard 페이지로 이동
- 로그아웃 상태: /sign-in 페이지로 이동 
- useAuth 훅을 통해 로그인 상태 가져와 조건 라우팅 (caeadef6f51bbaad10ac9d05d36c719d95e1faa3)
아주 조금 변경되어 따로 이슈나 브랜치를 만들지 않고 작업했습니다^^
> Feature(HK-138): 로그인 상태에 따른 시작하기 버튼 라우팅

- package-lock.json
- package.json
- src/api/keychains/keychain-update/index.tsx
- src/components/dashboard/button/index.tsx
- src/components/dashboard/button/saveButton/index.style.tsx
- src/components/dashboard/button/saveButton/index.tsx
- src/components/dashboard/cards/keychain-card/index.style.tsx
- src/components/dashboard/cards/keychain-card/index.tsx
- src/components/dashboard/modals/keychain-read-modal/handlers/index.tsx
- src/components/dashboard/modals/keychain-read-modal/index.tsx
- src/components/dashboard/modals/keychain-read-modal/inputGroup/index.tsx
- src/components/dashboard/modals/keychain-read-modal/types/index.tsx
- src/components/dashboard/modals/register-modal/index.tsx
- src/components/dashboard/modals/register-modal/types/index.tsx
- src/hooks/useModal/index.tsx
- src/pages/keychain/index.tsx
- [HK-125](https://team-dopamine.atlassian.net/browse/HK-125?atlOrigin=eyJpIjoiMGRiYzg3NWU4MzVlNDQwYjhmNTdiMGYzMGFhNjU4ZDMiLCJwIjoiaiJ9) 참고
- 사용자가 키체인 name 및 Private Key를 수정하기 위함
- 키체인 등록 모달창의 버튼 그룹 수정
- 케밥버튼 클릭 시 키체인 수정 및 삭제가 가능한 모달 열림
- 키체인 수정 api 연동
- font-awesome 라이브러리 설치했으나 타 브랜치에서 작업하기로 협의(004283954ff95757ed9431d375654cbfec9d0b4e)
- 버튼그룹 리팩토링하면서 삭제 호출 api도 같이 이관
- 핸들러 추가하여 api 호출 분리 ([6db79c9](https://github.com/team-dopamine/husk-web/pull/50/commits/6db79c969e83f6b61cdf7ed6a5e07ad91f608c1e))
- type 분리 ([d497551](https://github.com/team-dopamine/husk-web/pull/50/commits/d497551eab9de544efe3f71fcd0a115a949cac91))
- `useModal` 훅 분리 ([834ea8e](https://github.com/team-dopamine/husk-web/pull/50/commits/834ea8e7ceaad32b3794398ecd960b539ff78b4b))
- input 필드 분리 …
> Feature(HK-125): 키체인 수정 API 연동 및 수정 모달창 구현

- src/api/keychains/keychain-decrypt/index.tsx
- src/components/dashboard/button/index.style.tsx
- src/components/dashboard/button/index.tsx
- src/components/dashboard/cards/keychain-card/index.tsx
- src/components/dashboard/cards/register-card/index.style.tsx
- src/components/dashboard/modals/keychain-read-modal/index.style.tsx
- src/components/dashboard/modals/keychain-read-modal/index.tsx
- src/components/dashboard/modals/keychain-read-modal/inputGroup/index.tsx
- src/components/dashboard/modals/keychain-read-modal/types/index.tsx
- src/pages/keychain/index.tsx
- [(HK-127)](https://team-dopamine.atlassian.net/browse/HK-127) 참고
- 사용자가 키체인 값을 복호화하여 보기 위함
-  ( Update | Delete ) 버튼 중앙 정렬 및 update → Update로 텍스트 수정 ( dd518093ec8d1d5156c7664971ca3c2cebdd3e99),(bcf3775cf7d4b6e019ff64a096c5bd390385f334)
- key 누락 및 deprecated bodyStyle 경고 해결 (2cbcef11177ceb18e879ab6872d2c57c3f4217f1)
- 키체인 복호화 API 함수 및 관련 타입 정의 추가 (b0a51caf2957f1b5aceeb6a513358175e10a5cea)
- 키체인 복호화 API 연동 및 복호화 기능 구현 (1e075903b9f4e184658e2e2de1c6bf3f4a499f17), (af9277ec657f3dd73226a1223a05c67bc26a401d), (36ecd6eab9b457b8ed0410b43deab3ca85df4aa2)
🔐 키체인 값 마스킹 처리 방식 변경
- 기존: 고정된 길이의 `*******` 형태로 가짜 마스킹 값 렌더링
- 문제: 암호화된 상태로 값을 수정하기 힘듦 
- *******의 고정된 길이로 업데이트 시, 예: ******123 혹은 *******을 다 지운 상태로 값을 수정 
- 마스킹된 값을 수정할 때도 내부 실제 값을 따로 추적해야 해서 구현 복잡도 ↑
- 개선 방식: type = 'password' 속성 사용 
- 키체인 값 …
> Feature(HK-127): 키체인 복호화 API 연동 및 복호화 기능 추가

- src/App.tsx
- src/api/ssh-connections/index.tsx
- src/components/dashboard/layout/dashboard-sidebar/index.tsx
- src/pages/ssh-connection/index.style.tsx
- src/pages/ssh-connection/index.tsx
- [HK-130](https://team-dopamine.atlassian.net/browse/HK-122?atlOrigin=eyJpIjoiZWE1ODQwZGY2MmM3NGM0ZDgyNWViMjQ3NjIzZjVkNTgiLCJwIjoiaiJ9) 참고
- 사용자가 등록한 SSH 커넥션을 조회하여 확인하기 위함
- SSH 조회 api 연동 로직 구현(c38ab6c3de50020a6a6bf5e7a807e8ba505c0e91)
- SSH 커넥션 페이지 구현 (43ce18f70a641bf81128806b3d5d51ef5ac3693f)
- SSH 조회 api 연동 (43ce18f70a641bf81128806b3d5d51ef5ac3693f)
- 페이지 경로 설정 및 사이드 바 클릭 시 해당 경로 이동 (2f5bc469eb96156c378e90d811b17d931b2b8e22)
- 공통 구조를 export 해서 사용할 수 있도록 리팩토링(64f29b298d2958ce8b1b80cbd96acdb147747994)
- 스타일 margin을 스타일 컴포넌트 파일로 이동 (a4909c3)
[HK-130]: https://team-dopamine.atlassian.net/browse/HK-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-130): SSH 커넥션 조회 api 연동

- src/components/dashboard/cards/sshConnection-card/index.tsx
- src/components/dashboard/modals/sshConnection/index.tsx
- src/pages/ssh-connection/index.tsx
- 키체인컴포넌트 중복 사용으로 코드 복잡성 대두
- SSH용 카드 컴포넌트 구현(7e28367dbe58c83de2989ce350db07febbf0da27),(88d21d4092877c8de5c1d7123b8f32bba9d92362)
- 케밥버튼 클릭 시 임시 모달창 구현(b217bafc7cbde1ab9247e10c4c45378606ed6a38)
- 삭제 api 구현하면서 모달창에 버튼 따로 추가하겠습니다!
> Refactor(HK-151): SSH 관련 컴포넌트 리팩토링

- src/api/ssh-connections/ssh-delete/index.tsx
- src/components/dashboard/cards/sshConnection-card/index.tsx
- src/components/dashboard/modals/register-modal/index.tsx
- src/components/dashboard/modals/register-modal/types/index.tsx
- src/components/dashboard/modals/sshConnection/handlers/index.tsx
- src/components/dashboard/modals/sshConnection/index.tsx
- src/components/dashboard/modals/types/index.tsx
- [HK-144](https://team-dopamine.atlassian.net/browse/HK-144?atlOrigin=eyJpIjoiMDk5NmZlODRhYjUzNDA2Mjg5ZDA4N2Q3MjRhNTdkOGYiLCJwIjoiaiJ9) 참고
- 사용자가 저장한 SSH 커넥션을 삭제하기 위함
- ssh 커넥션 삭제 api 호출 로직 구현(52850451d4c46d40ebd3991ea1f828eb49120963)
- 키체인/ssh커넥션 ReadModal 분리에 의한 props 타입 분리 (480d3f440c41be1879ed7f8b7a8d79bcc0b5293b)
- api 호출 핸들러 구현하여 삭제 api 연동(281609fe8278401ece5e2b5181560a5a7de4c3a8), (37a33fcf37017d9284692d77955ef1ac3233fcbd)
- 삭제 api 호출 성공 시 화면 새로고침
- 우선 모달창에 이전 버튼그룹 컴포넌트(`update|delete` 버튼) 그대로 가져와서 사용하고 있습니다. 추후 수정 api 연동 시 참고해주시면 됩니다::)
[HK-144]: https://team-dopamine.atlassian.net/browse/HK-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-144): SSH 커넥션 삭제 API 연동

- src/assets/Login.svg
- src/components/dashboard/button/saveButton/index.style.tsx
- src/components/dashboard/button/saveButton/index.tsx
- src/components/dashboard/modals/register-modal/index.style.tsx
- src/components/dashboard/modals/register-modal/index.tsx
- src/components/header/index.style.tsx
- src/components/header/index.tsx
- src/pages/sign-up/content/password/content/index.style.tsx
- src/pages/sign-up/content/password/content/index.tsx
- `Login`, `Logout` 버튼을 아이콘으로 수정하기 위함
- 비밀번호 설정 영역에서 경고 메시지가 버튼과 겹치는 현상 수정
- SSH Connection부분
- Connection Name필드에 띄어쓰기를 포함하면 에러 문구 발생
- 모든 입력 필드를 작성하지 않을 경우, 버튼 비활성화
- 로그인/로그아웃 버튼을 아이콘으로 변경  
(commit: 56ae2ff8d2d7c77db93f8dc87db8a578cea16e45)
- 비밀번호 설정 시:
- 경고 메시지가 버튼과 겹치는 문제 수정  
(5126bd214115485806ea003088bc566f0a39de62)  
- 입력값을 모두 삭제해도 경고 메시지가 남아있는 문제 수정  
(5126bd214115485806ea003088bc566f0a39de62)  
- 공백 입력 시 경고 문구 표시 및 버튼 활성화(c7dff3885a69011305332a0c9988213cbf4c1cc3)
https://github.com/team-dopamine/husk-web/pull/71#discussion_r2312440710 
- ```코드 리뷰 반영 전``` 
- ```코드 리뷰 반영 후``` 
코드 리뷰 반영해서 다시 올렸습니다~
확인해 주세요!
> Refactor(HK-163): 세부부분 수정

- src/pages/sign-in/sign-in-email/content/index.tsx
- [HK-166](https://team-dopamine.atlassian.net/browse/HK-166) 참고
- 사용자가 이메일 로그인 시 이메일을 저장하고자 함
- **Remember Email** 체크박스 UI 추가
- 체크박스 선택 시 입력한 이메일을 `쿠키`에 저장(30일 유지)
- 체크 상태면 쿠키에 이메일 저장
- 해제 상태면 쿠키 삭제
- 초기 렌더링 시 저장된 이메일이 있으면 자동 입력 & 체크박스 활성화
- `Sign In` 페이지가 전반적으로 영문이라 영어로 작성해두었는데 추후 언어 통일 협의 필요할 것 같습니다!
[HK-166]: https://team-dopamine.atlassian.net/browse/HK-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature(HK-166): 이메일 저장하기 로직 구현
